### PR TITLE
Hexgrid

### PR DESCRIPTION
**Pull request by maka0945**
Been messing around with this hex grid let me know what you think

### CODE REVIEW

**Comment by maka0945** [comment]
@mrshannon

**Comment by mrshannon** [comment]
First of all, impressive demo.  Now for the issues.

You are going to need to make another branch and re-commit because below are the files we either should not have or can't have in the repo.

- Hexagons_rebooted.sln - this is a visual studio file
- Web.Debug.config - also a visual studio file
- Web.config - again, another visual studio file
- jquery-ui.min.css - external library
- css/images (entire directory - move background.jpg to main images folder)
- jquery-ui.min.js - external library

Beyond that, all JS files must use require/module.exports style (unless they are browser side only - which none of these are - but one needs to be).  For instance, proper way to include jquery in a Node app is:
```
const $ = window.jQuery = require('jquery');
```
I can talk you through the specifics via commit comments after the first issue is fixed.

To handle jquery-ui you need to use https://www.npmjs.com/package/jquery-ui.

Once you recommit-in a fresh branch without the above files I will markup the actual commit for specific problems.

**Comment by maka0945** [comment]
Cool I'll get on that right now, just wanted your opinion before proceeding

**Comment by mrshannon** [comment]
FYI, in the future, when unsure about whether you should commit a file don't commit it.  It is much easier to add a file than to remove one.

**Comment by maka0945** [comment]
Yeah did that by accident... didn't know i was in the master file

**Pull request closed without merging**
